// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadStatus_Status int32

const (
	UploadStatus_INVALID_PATH UploadStatus_Status = 0
	UploadStatus_FILE_EXISTS  UploadStatus_Status = 1
	UploadStatus_UPLOADING    UploadStatus_Status = 2
	UploadStatus_CANCELLED    UploadStatus_Status = 3
)

// Enum value maps for UploadStatus_Status.
var (
	UploadStatus_Status_name = map[int32]string{
		0: "INVALID_PATH",
		1: "FILE_EXISTS",
		2: "UPLOADING",
		3: "CANCELLED",
	}
	UploadStatus_Status_value = map[string]int32{
		"INVALID_PATH": 0,
		"FILE_EXISTS":  1,
		"UPLOADING":    2,
		"CANCELLED":    3,
	}
)

func (x UploadStatus_Status) Enum() *UploadStatus_Status {
	p := new(UploadStatus_Status)
	*p = x
	return p
}

func (x UploadStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_proto_enumTypes[0].Descriptor()
}

func (UploadStatus_Status) Type() protoreflect.EnumType {
	return &file_api_api_proto_enumTypes[0]
}

func (x UploadStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatus_Status.Descriptor instead.
func (UploadStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{6, 0}
}

type LibraryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"fixed64,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryRequest) Reset() {
	*x = LibraryRequest{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryRequest) ProtoMessage() {}

func (x *LibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryRequest.ProtoReflect.Descriptor instead.
func (*LibraryRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *LibraryRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type LibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"fixed64,1,opt,name=index,proto3" json:"index,omitempty"`
	AddIndex      []*File                `protobuf:"bytes,2,rep,name=add_index,json=addIndex,proto3" json:"add_index,omitempty"`
	RemoveIndex   []*File                `protobuf:"bytes,3,rep,name=remove_index,json=removeIndex,proto3" json:"remove_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryResponse) Reset() {
	*x = LibraryResponse{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryResponse) ProtoMessage() {}

func (x *LibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryResponse.ProtoReflect.Descriptor instead.
func (*LibraryResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *LibraryResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LibraryResponse) GetAddIndex() []*File {
	if x != nil {
		return x.AddIndex
	}
	return nil
}

func (x *LibraryResponse) GetRemoveIndex() []*File {
	if x != nil {
		return x.RemoveIndex
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        string                 `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`
	Track         string                 `protobuf:"bytes,3,opt,name=track,proto3" json:"track,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *File) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *File) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

func (x *File) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*UploadRequest_Path
	//	*UploadRequest_Data
	Request       isUploadRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *UploadRequest) GetRequest() isUploadRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *UploadRequest) GetPath() string {
	if x != nil {
		if x, ok := x.Request.(*UploadRequest_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*UploadRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadRequest_Request interface {
	isUploadRequest_Request()
}

type UploadRequest_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type UploadRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadRequest_Path) isUploadRequest_Request() {}

func (*UploadRequest_Data) isUploadRequest_Request() {}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        UploadStatus_Status    `protobuf:"varint,4,opt,name=status,proto3,enum=api.UploadStatus_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_api_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *UploadStatus) GetStatus() UploadStatus_Status {
	if x != nil {
		return x.Status
	}
	return UploadStatus_INVALID_PATH
}

type UploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*UploadResponse_Status
	//	*UploadResponse_Progress
	Response      isUploadResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_api_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *UploadResponse) GetResponse() isUploadResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UploadResponse) GetStatus() *UploadStatus {
	if x != nil {
		if x, ok := x.Response.(*UploadResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *UploadResponse) GetProgress() int64 {
	if x != nil {
		if x, ok := x.Response.(*UploadResponse_Progress); ok {
			return x.Progress
		}
	}
	return 0
}

type isUploadResponse_Response interface {
	isUploadResponse_Response()
}

type UploadResponse_Status struct {
	Status *UploadStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type UploadResponse_Progress struct {
	Progress int64 `protobuf:"varint,2,opt,name=progress,proto3,oneof"`
}

func (*UploadResponse_Status) isUploadResponse_Response() {}

func (*UploadResponse_Progress) isUploadResponse_Response() {}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x03api\"&\n" +
	"\x0eLibraryRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x06R\x05index\"}\n" +
	"\x0fLibraryResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x06R\x05index\x12&\n" +
	"\tadd_index\x18\x02 \x03(\v2\t.api.FileR\baddIndex\x12,\n" +
	"\fremove_index\x18\x03 \x03(\v2\t.api.FileR\vremoveIndex\"z\n" +
	"\x04File\x12\x16\n" +
	"\x06artist\x18\x01 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x02 \x01(\tR\x05album\x12\x14\n" +
	"\x05track\x18\x03 \x01(\tR\x05track\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"%\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\x10DownloadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"F\n" +
	"\rUploadRequest\x12\x14\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\arequest\"\x8b\x01\n" +
	"\fUploadStatus\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.api.UploadStatus.StatusR\x06status\"I\n" +
	"\x06Status\x12\x10\n" +
	"\fINVALID_PATH\x10\x00\x12\x0f\n" +
	"\vFILE_EXISTS\x10\x01\x12\r\n" +
	"\tUPLOADING\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\"g\n" +
	"\x0eUploadResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x11.api.UploadStatusH\x00R\x06status\x12\x1c\n" +
	"\bprogress\x18\x02 \x01(\x03H\x00R\bprogressB\n" +
	"\n" +
	"\bresponse2|\n" +
	"\aLibrary\x124\n" +
	"\x03Get\x12\x13.api.LibraryRequest\x1a\x14.api.LibraryResponse\"\x000\x01\x12;\n" +
	"\bDownload\x12\x14.api.DownloadRequest\x1a\x15.api.DownloadResponse\"\x000\x012B\n" +
	"\aDupload\x127\n" +
	"\x06Upload\x12\x12.api.UploadRequest\x1a\x13.api.UploadResponse\"\x00(\x010\x01B\x1eZ\x1cgithub.com/bh90210/super/apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_api_proto_goTypes = []any{
	(UploadStatus_Status)(0), // 0: api.UploadStatus.Status
	(*LibraryRequest)(nil),   // 1: api.LibraryRequest
	(*LibraryResponse)(nil),  // 2: api.LibraryResponse
	(*File)(nil),             // 3: api.File
	(*DownloadRequest)(nil),  // 4: api.DownloadRequest
	(*DownloadResponse)(nil), // 5: api.DownloadResponse
	(*UploadRequest)(nil),    // 6: api.UploadRequest
	(*UploadStatus)(nil),     // 7: api.UploadStatus
	(*UploadResponse)(nil),   // 8: api.UploadResponse
}
var file_api_api_proto_depIdxs = []int32{
	3, // 0: api.LibraryResponse.add_index:type_name -> api.File
	3, // 1: api.LibraryResponse.remove_index:type_name -> api.File
	0, // 2: api.UploadStatus.status:type_name -> api.UploadStatus.Status
	7, // 3: api.UploadResponse.status:type_name -> api.UploadStatus
	1, // 4: api.Library.Get:input_type -> api.LibraryRequest
	4, // 5: api.Library.Download:input_type -> api.DownloadRequest
	6, // 6: api.Dupload.Upload:input_type -> api.UploadRequest
	2, // 7: api.Library.Get:output_type -> api.LibraryResponse
	5, // 8: api.Library.Download:output_type -> api.DownloadResponse
	8, // 9: api.Dupload.Upload:output_type -> api.UploadResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	file_api_api_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadRequest_Path)(nil),
		(*UploadRequest_Data)(nil),
	}
	file_api_api_proto_msgTypes[7].OneofWrappers = []any{
		(*UploadResponse_Status)(nil),
		(*UploadResponse_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		EnumInfos:         file_api_api_proto_enumTypes,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
