FROM --platform=$BUILDPLATFORM golang:1.25.5 AS builder
ARG TARGETOS
ARG TARGETARCH
WORKDIR /super
COPY ./ ./
WORKDIR /super/auto
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} CGO_ENABLED=0 go build -o ./auto


FROM scratch
WORKDIR /auto
COPY --from=builder /super/auto/auto ./auto
EXPOSE 3000
EXPOSE 3005
EXPOSE 2112
ENTRYPOINT ["./auto"]
