# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build-push-docker:
    desc: Build the server Docker image locally for testing.
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/bh90210/server:latest .
      - docker push ghcr.io/bh90210/server:latest