# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build-api:
    desc: Build the server gRPC API go stubs. preconditions install Protocol buffer compiler, protoc and Go plugins for the protocol compiler. For more info see https://grpc.io/docs/languages/go/quickstart/.
    preconditions:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    cmds: 
      - PATH="$PATH:$(go env GOPATH)/bin" protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative api/api.proto

  test-build-push-docker:
    desc: Build the server Docker image locally for testing.
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/bh90210/server:latest .
      - docker push ghcr.io/bh90210/server:latest