// protoc --go_out=. --go_opt=paths=source_relative \
//  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//  auto/api/auto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auto/api/auto.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookResponse) Reset() {
	*x = WebhookResponse{}
	mi := &file_auto_api_auto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookResponse) ProtoMessage() {}

func (x *WebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auto_api_auto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookResponse.ProtoReflect.Descriptor instead.
func (*WebhookResponse) Descriptor() ([]byte, []int) {
	return file_auto_api_auto_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_auto_api_auto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_auto_api_auto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_auto_api_auto_proto_rawDescGZIP(), []int{1}
}

var File_auto_api_auto_proto protoreflect.FileDescriptor

const file_auto_api_auto_proto_rawDesc = "" +
	"\n" +
	"\x13auto/api/auto.proto\x12\x03api\"%\n" +
	"\x0fWebhookResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\a\n" +
	"\x05Empty29\n" +
	"\x06Github\x12/\n" +
	"\aWebhook\x12\n" +
	".api.Empty\x1a\x14.api.WebhookResponse\"\x000\x01B#Z!github.com/bh90210/super/auto/apib\x06proto3"

var (
	file_auto_api_auto_proto_rawDescOnce sync.Once
	file_auto_api_auto_proto_rawDescData []byte
)

func file_auto_api_auto_proto_rawDescGZIP() []byte {
	file_auto_api_auto_proto_rawDescOnce.Do(func() {
		file_auto_api_auto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auto_api_auto_proto_rawDesc), len(file_auto_api_auto_proto_rawDesc)))
	})
	return file_auto_api_auto_proto_rawDescData
}

var file_auto_api_auto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auto_api_auto_proto_goTypes = []any{
	(*WebhookResponse)(nil), // 0: api.WebhookResponse
	(*Empty)(nil),           // 1: api.Empty
}
var file_auto_api_auto_proto_depIdxs = []int32{
	1, // 0: api.Github.Webhook:input_type -> api.Empty
	0, // 1: api.Github.Webhook:output_type -> api.WebhookResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auto_api_auto_proto_init() }
func file_auto_api_auto_proto_init() {
	if File_auto_api_auto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auto_api_auto_proto_rawDesc), len(file_auto_api_auto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auto_api_auto_proto_goTypes,
		DependencyIndexes: file_auto_api_auto_proto_depIdxs,
		MessageInfos:      file_auto_api_auto_proto_msgTypes,
	}.Build()
	File_auto_api_auto_proto = out.File
	file_auto_api_auto_proto_goTypes = nil
	file_auto_api_auto_proto_depIdxs = nil
}
