// protoc --go_out=. --go_opt=paths=source_relative \
//  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//  auto/api/auto.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: auto/api/auto.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Github_Webhook_FullMethodName = "/api.Github/Webhook"
)

// GithubClient is the client API for Github service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GithubClient interface {
	Webhook(ctx context.Context, in *WebhookRequest, opts ...grpc.CallOption) (*Empty, error)
}

type githubClient struct {
	cc grpc.ClientConnInterface
}

func NewGithubClient(cc grpc.ClientConnInterface) GithubClient {
	return &githubClient{cc}
}

func (c *githubClient) Webhook(ctx context.Context, in *WebhookRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Github_Webhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubServer is the server API for Github service.
// All implementations must embed UnimplementedGithubServer
// for forward compatibility.
type GithubServer interface {
	Webhook(context.Context, *WebhookRequest) (*Empty, error)
	mustEmbedUnimplementedGithubServer()
}

// UnimplementedGithubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGithubServer struct{}

func (UnimplementedGithubServer) Webhook(context.Context, *WebhookRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Webhook not implemented")
}
func (UnimplementedGithubServer) mustEmbedUnimplementedGithubServer() {}
func (UnimplementedGithubServer) testEmbeddedByValue()                {}

// UnsafeGithubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GithubServer will
// result in compilation errors.
type UnsafeGithubServer interface {
	mustEmbedUnimplementedGithubServer()
}

func RegisterGithubServer(s grpc.ServiceRegistrar, srv GithubServer) {
	// If the following call panics, it indicates UnimplementedGithubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Github_ServiceDesc, srv)
}

func _Github_Webhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).Webhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Github_Webhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).Webhook(ctx, req.(*WebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Github_ServiceDesc is the grpc.ServiceDesc for Github service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Github_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Github",
	HandlerType: (*GithubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Webhook",
			Handler:    _Github_Webhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auto/api/auto.proto",
}
