// protoc --go_out=. --go_opt=paths=source_relative \
//  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//  auto/api/auto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auto/api/auto.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hook_Type int32

const (
	Hook_PUSH    Hook_Type = 0
	Hook_REGPUSH Hook_Type = 1
	Hook_RELEASE Hook_Type = 2
	Hook_TAG     Hook_Type = 3
)

// Enum value maps for Hook_Type.
var (
	Hook_Type_name = map[int32]string{
		0: "PUSH",
		1: "REGPUSH",
		2: "RELEASE",
		3: "TAG",
	}
	Hook_Type_value = map[string]int32{
		"PUSH":    0,
		"REGPUSH": 1,
		"RELEASE": 2,
		"TAG":     3,
	}
)

func (x Hook_Type) Enum() *Hook_Type {
	p := new(Hook_Type)
	*p = x
	return p
}

func (x Hook_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hook_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_auto_api_auto_proto_enumTypes[0].Descriptor()
}

func (Hook_Type) Type() protoreflect.EnumType {
	return &file_auto_api_auto_proto_enumTypes[0]
}

func (x Hook_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hook_Type.Descriptor instead.
func (Hook_Type) EnumDescriptor() ([]byte, []int) {
	return file_auto_api_auto_proto_rawDescGZIP(), []int{1, 0}
}

type WebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Hooktype      *Hook                  `protobuf:"bytes,2,opt,name=hooktype,proto3" json:"hooktype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookResponse) Reset() {
	*x = WebhookResponse{}
	mi := &file_auto_api_auto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookResponse) ProtoMessage() {}

func (x *WebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auto_api_auto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookResponse.ProtoReflect.Descriptor instead.
func (*WebhookResponse) Descriptor() ([]byte, []int) {
	return file_auto_api_auto_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WebhookResponse) GetHooktype() *Hook {
	if x != nil {
		return x.Hooktype
	}
	return nil
}

type Hook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Hook_Type              `protobuf:"varint,5,opt,name=type,proto3,enum=api.Hook_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hook) Reset() {
	*x = Hook{}
	mi := &file_auto_api_auto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hook) ProtoMessage() {}

func (x *Hook) ProtoReflect() protoreflect.Message {
	mi := &file_auto_api_auto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hook.ProtoReflect.Descriptor instead.
func (*Hook) Descriptor() ([]byte, []int) {
	return file_auto_api_auto_proto_rawDescGZIP(), []int{1}
}

func (x *Hook) GetType() Hook_Type {
	if x != nil {
		return x.Type
	}
	return Hook_PUSH
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_auto_api_auto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_auto_api_auto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_auto_api_auto_proto_rawDescGZIP(), []int{2}
}

var File_auto_api_auto_proto protoreflect.FileDescriptor

const file_auto_api_auto_proto_rawDesc = "" +
	"\n" +
	"\x13auto/api/auto.proto\x12\x03api\"L\n" +
	"\x0fWebhookResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12%\n" +
	"\bhooktype\x18\x02 \x01(\v2\t.api.HookR\bhooktype\"_\n" +
	"\x04Hook\x12\"\n" +
	"\x04type\x18\x05 \x01(\x0e2\x0e.api.Hook.TypeR\x04type\"3\n" +
	"\x04Type\x12\b\n" +
	"\x04PUSH\x10\x00\x12\v\n" +
	"\aREGPUSH\x10\x01\x12\v\n" +
	"\aRELEASE\x10\x02\x12\a\n" +
	"\x03TAG\x10\x03\"\a\n" +
	"\x05Empty29\n" +
	"\x06Github\x12/\n" +
	"\aWebhook\x12\n" +
	".api.Empty\x1a\x14.api.WebhookResponse\"\x000\x01B#Z!github.com/bh90210/super/auto/apib\x06proto3"

var (
	file_auto_api_auto_proto_rawDescOnce sync.Once
	file_auto_api_auto_proto_rawDescData []byte
)

func file_auto_api_auto_proto_rawDescGZIP() []byte {
	file_auto_api_auto_proto_rawDescOnce.Do(func() {
		file_auto_api_auto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auto_api_auto_proto_rawDesc), len(file_auto_api_auto_proto_rawDesc)))
	})
	return file_auto_api_auto_proto_rawDescData
}

var file_auto_api_auto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auto_api_auto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auto_api_auto_proto_goTypes = []any{
	(Hook_Type)(0),          // 0: api.Hook.Type
	(*WebhookResponse)(nil), // 1: api.WebhookResponse
	(*Hook)(nil),            // 2: api.Hook
	(*Empty)(nil),           // 3: api.Empty
}
var file_auto_api_auto_proto_depIdxs = []int32{
	2, // 0: api.WebhookResponse.hooktype:type_name -> api.Hook
	0, // 1: api.Hook.type:type_name -> api.Hook.Type
	3, // 2: api.Github.Webhook:input_type -> api.Empty
	1, // 3: api.Github.Webhook:output_type -> api.WebhookResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auto_api_auto_proto_init() }
func file_auto_api_auto_proto_init() {
	if File_auto_api_auto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auto_api_auto_proto_rawDesc), len(file_auto_api_auto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auto_api_auto_proto_goTypes,
		DependencyIndexes: file_auto_api_auto_proto_depIdxs,
		EnumInfos:         file_auto_api_auto_proto_enumTypes,
		MessageInfos:      file_auto_api_auto_proto_msgTypes,
	}.Build()
	File_auto_api_auto_proto = out.File
	file_auto_api_auto_proto_goTypes = nil
	file_auto_api_auto_proto_depIdxs = nil
}
