// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

export function Init(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2301252281, app);
}

export function List(): $CancellablePromise<api$0.File[]> {
    return $Call.ByID(3315069575).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.File.createFrom;
const $$createType1 = $Create.Array($$createType0);
