// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LibraryClient is the client API for Library service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LibraryClient interface {
	Get(ctx context.Context, in *LibraryRequest, opts ...grpc.CallOption) (Library_GetClient, error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (Library_DownloadClient, error)
}

type libraryClient struct {
	cc grpc.ClientConnInterface
}

func NewLibraryClient(cc grpc.ClientConnInterface) LibraryClient {
	return &libraryClient{cc}
}

func (c *libraryClient) Get(ctx context.Context, in *LibraryRequest, opts ...grpc.CallOption) (Library_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &Library_ServiceDesc.Streams[0], "/api.Library/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &libraryGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Library_GetClient interface {
	Recv() (*LibraryResponse, error)
	grpc.ClientStream
}

type libraryGetClient struct {
	grpc.ClientStream
}

func (x *libraryGetClient) Recv() (*LibraryResponse, error) {
	m := new(LibraryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *libraryClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (Library_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Library_ServiceDesc.Streams[1], "/api.Library/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &libraryDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Library_DownloadClient interface {
	Recv() (*DownloadResponse, error)
	grpc.ClientStream
}

type libraryDownloadClient struct {
	grpc.ClientStream
}

func (x *libraryDownloadClient) Recv() (*DownloadResponse, error) {
	m := new(DownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LibraryServer is the server API for Library service.
// All implementations must embed UnimplementedLibraryServer
// for forward compatibility
type LibraryServer interface {
	Get(*LibraryRequest, Library_GetServer) error
	Download(*DownloadRequest, Library_DownloadServer) error
	mustEmbedUnimplementedLibraryServer()
}

// UnimplementedLibraryServer must be embedded to have forward compatible implementations.
type UnimplementedLibraryServer struct {
}

func (UnimplementedLibraryServer) Get(*LibraryRequest, Library_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLibraryServer) Download(*DownloadRequest, Library_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedLibraryServer) mustEmbedUnimplementedLibraryServer() {}

// UnsafeLibraryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LibraryServer will
// result in compilation errors.
type UnsafeLibraryServer interface {
	mustEmbedUnimplementedLibraryServer()
}

func RegisterLibraryServer(s grpc.ServiceRegistrar, srv LibraryServer) {
	s.RegisterService(&Library_ServiceDesc, srv)
}

func _Library_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LibraryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LibraryServer).Get(m, &libraryGetServer{stream})
}

type Library_GetServer interface {
	Send(*LibraryResponse) error
	grpc.ServerStream
}

type libraryGetServer struct {
	grpc.ServerStream
}

func (x *libraryGetServer) Send(m *LibraryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Library_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LibraryServer).Download(m, &libraryDownloadServer{stream})
}

type Library_DownloadServer interface {
	Send(*DownloadResponse) error
	grpc.ServerStream
}

type libraryDownloadServer struct {
	grpc.ServerStream
}

func (x *libraryDownloadServer) Send(m *DownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Library_ServiceDesc is the grpc.ServiceDesc for Library service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Library_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Library",
	HandlerType: (*LibraryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _Library_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _Library_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/api.proto",
}

// DuploadClient is the client API for Dupload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DuploadClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (Dupload_UploadClient, error)
}

type duploadClient struct {
	cc grpc.ClientConnInterface
}

func NewDuploadClient(cc grpc.ClientConnInterface) DuploadClient {
	return &duploadClient{cc}
}

func (c *duploadClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Dupload_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Dupload_ServiceDesc.Streams[0], "/api.Dupload/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &duploadUploadClient{stream}
	return x, nil
}

type Dupload_UploadClient interface {
	Send(*UploadRequest) error
	Recv() (*UploadResponse, error)
	grpc.ClientStream
}

type duploadUploadClient struct {
	grpc.ClientStream
}

func (x *duploadUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *duploadUploadClient) Recv() (*UploadResponse, error) {
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DuploadServer is the server API for Dupload service.
// All implementations must embed UnimplementedDuploadServer
// for forward compatibility
type DuploadServer interface {
	Upload(Dupload_UploadServer) error
	mustEmbedUnimplementedDuploadServer()
}

// UnimplementedDuploadServer must be embedded to have forward compatible implementations.
type UnimplementedDuploadServer struct {
}

func (UnimplementedDuploadServer) Upload(Dupload_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedDuploadServer) mustEmbedUnimplementedDuploadServer() {}

// UnsafeDuploadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DuploadServer will
// result in compilation errors.
type UnsafeDuploadServer interface {
	mustEmbedUnimplementedDuploadServer()
}

func RegisterDuploadServer(s grpc.ServiceRegistrar, srv DuploadServer) {
	s.RegisterService(&Dupload_ServiceDesc, srv)
}

func _Dupload_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DuploadServer).Upload(&duploadUploadServer{stream})
}

type Dupload_UploadServer interface {
	Send(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type duploadUploadServer struct {
	grpc.ServerStream
}

func (x *duploadUploadServer) Send(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *duploadUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Dupload_ServiceDesc is the grpc.ServiceDesc for Dupload service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dupload_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Dupload",
	HandlerType: (*DuploadServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Dupload_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/api.proto",
}
