// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/authservice.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowType int32

const (
	FlowType_FLOW_TYPE_UNSPECIFIED FlowType = 0
	FlowType_FLOW_TYPE_LOGIN       FlowType = 1 // Standard Email OTP Login
	FlowType_FLOW_TYPE_RECOVERY    FlowType = 2 // Redeeming Email Invite OTP
)

// Enum value maps for FlowType.
var (
	FlowType_name = map[int32]string{
		0: "FLOW_TYPE_UNSPECIFIED",
		1: "FLOW_TYPE_LOGIN",
		2: "FLOW_TYPE_RECOVERY",
	}
	FlowType_value = map[string]int32{
		"FLOW_TYPE_UNSPECIFIED": 0,
		"FLOW_TYPE_LOGIN":       1,
		"FLOW_TYPE_RECOVERY":    2,
	}
)

func (x FlowType) Enum() *FlowType {
	p := new(FlowType)
	*p = x
	return p
}

func (x FlowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_authservice_proto_enumTypes[0].Descriptor()
}

func (FlowType) Type() protoreflect.EnumType {
	return &file_api_authservice_proto_enumTypes[0]
}

func (x FlowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowType.Descriptor instead.
func (FlowType) EnumDescriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{0}
}

type InitializeFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FlowType               `protobuf:"varint,1,opt,name=type,proto3,enum=api.FlowType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeFlowRequest) Reset() {
	*x = InitializeFlowRequest{}
	mi := &file_api_authservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeFlowRequest) ProtoMessage() {}

func (x *InitializeFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeFlowRequest.ProtoReflect.Descriptor instead.
func (*InitializeFlowRequest) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeFlowRequest) GetType() FlowType {
	if x != nil {
		return x.Type
	}
	return FlowType_FLOW_TYPE_UNSPECIFIED
}

type InitializeFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeFlowResponse) Reset() {
	*x = InitializeFlowResponse{}
	mi := &file_api_authservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeFlowResponse) ProtoMessage() {}

func (x *InitializeFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeFlowResponse.ProtoReflect.Descriptor instead.
func (*InitializeFlowResponse) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeFlowResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

// Triggers Kratos to dispatch a fresh 6-digit OTP code to the user's email
type RequestLoginCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLoginCodeRequest) Reset() {
	*x = RequestLoginCodeRequest{}
	mi := &file_api_authservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLoginCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLoginCodeRequest) ProtoMessage() {}

func (x *RequestLoginCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLoginCodeRequest.ProtoReflect.Descriptor instead.
func (*RequestLoginCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{2}
}

func (x *RequestLoginCodeRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *RequestLoginCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RequestLoginCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeSent      bool                   `protobuf:"varint,1,opt,name=code_sent,json=codeSent,proto3" json:"code_sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLoginCodeResponse) Reset() {
	*x = RequestLoginCodeResponse{}
	mi := &file_api_authservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLoginCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLoginCodeResponse) ProtoMessage() {}

func (x *RequestLoginCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLoginCodeResponse.ProtoReflect.Descriptor instead.
func (*RequestLoginCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{3}
}

func (x *RequestLoginCodeResponse) GetCodeSent() bool {
	if x != nil {
		return x.CodeSent
	}
	return false
}

type SubmitAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"` // The OTP code received in the email
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAuthRequest) Reset() {
	*x = SubmitAuthRequest{}
	mi := &file_api_authservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAuthRequest) ProtoMessage() {}

func (x *SubmitAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAuthRequest.ProtoReflect.Descriptor instead.
func (*SubmitAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAuthRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *SubmitAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubmitAuthRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SubmitAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Identity      *UserIdentity          `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAuthResponse) Reset() {
	*x = SubmitAuthResponse{}
	mi := &file_api_authservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAuthResponse) ProtoMessage() {}

func (x *SubmitAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAuthResponse.ProtoReflect.Descriptor instead.
func (*SubmitAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitAuthResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *SubmitAuthResponse) GetIdentity() *UserIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type InviteUserRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Email              string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Traits             map[string]string      `protobuf:"bytes,2,rep,name=traits,proto3" json:"traits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., name, role
	SendEmailViaKratos bool                   `protobuf:"varint,3,opt,name=send_email_via_kratos,json=sendEmailViaKratos,proto3" json:"send_email_via_kratos,omitempty"`                    // If true, Kratos/Courier emails the code directly
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InviteUserRequest) Reset() {
	*x = InviteUserRequest{}
	mi := &file_api_authservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserRequest) ProtoMessage() {}

func (x *InviteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserRequest.ProtoReflect.Descriptor instead.
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{6}
}

func (x *InviteUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteUserRequest) GetTraits() map[string]string {
	if x != nil {
		return x.Traits
	}
	return nil
}

func (x *InviteUserRequest) GetSendEmailViaKratos() bool {
	if x != nil {
		return x.SendEmailViaKratos
	}
	return false
}

type InviteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	RecoveryCode  string                 `protobuf:"bytes,2,opt,name=recovery_code,json=recoveryCode,proto3" json:"recovery_code,omitempty"` // Returned if send_email_via_kratos is false (for custom email templates)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserResponse) Reset() {
	*x = InviteUserResponse{}
	mi := &file_api_authservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserResponse) ProtoMessage() {}

func (x *InviteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserResponse.ProtoReflect.Descriptor instead.
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{7}
}

func (x *InviteUserResponse) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *InviteUserResponse) GetRecoveryCode() string {
	if x != nil {
		return x.RecoveryCode
	}
	return ""
}

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_api_authservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{8}
}

func (x *WhoAmIRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Identity      *UserIdentity          `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_api_authservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{9}
}

func (x *WhoAmIResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *WhoAmIResponse) GetIdentity() *UserIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_authservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_api_authservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Traits        map[string]string      `protobuf:"bytes,3,rep,name=traits,proto3" json:"traits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_api_authservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_authservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_api_authservice_proto_rawDescGZIP(), []int{12}
}

func (x *UserIdentity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserIdentity) GetTraits() map[string]string {
	if x != nil {
		return x.Traits
	}
	return nil
}

var File_api_authservice_proto protoreflect.FileDescriptor

const file_api_authservice_proto_rawDesc = "" +
	"\n" +
	"\x15api/authservice.proto\x12\x03api\":\n" +
	"\x15InitializeFlowRequest\x12!\n" +
	"\x04type\x18\x01 \x01(\x0e2\r.api.FlowTypeR\x04type\"1\n" +
	"\x16InitializeFlowResponse\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"H\n" +
	"\x17RequestLoginCodeRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"7\n" +
	"\x18RequestLoginCodeResponse\x12\x1b\n" +
	"\tcode_sent\x18\x01 \x01(\bR\bcodeSent\"V\n" +
	"\x11SubmitAuthRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"h\n" +
	"\x12SubmitAuthResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12-\n" +
	"\bidentity\x18\x02 \x01(\v2\x11.api.UserIdentityR\bidentity\"\xd3\x01\n" +
	"\x11InviteUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12:\n" +
	"\x06traits\x18\x02 \x03(\v2\".api.InviteUserRequest.TraitsEntryR\x06traits\x121\n" +
	"\x15send_email_via_kratos\x18\x03 \x01(\bR\x12sendEmailViaKratos\x1a9\n" +
	"\vTraitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x12InviteUserResponse\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12#\n" +
	"\rrecovery_code\x18\x02 \x01(\tR\frecoveryCode\"4\n" +
	"\rWhoAmIRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"W\n" +
	"\x0eWhoAmIResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12-\n" +
	"\bidentity\x18\x02 \x01(\v2\x11.api.UserIdentityR\bidentity\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa6\x01\n" +
	"\fUserIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x125\n" +
	"\x06traits\x18\x03 \x03(\v2\x1d.api.UserIdentity.TraitsEntryR\x06traits\x1a9\n" +
	"\vTraitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*R\n" +
	"\bFlowType\x12\x19\n" +
	"\x15FLOW_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFLOW_TYPE_LOGIN\x10\x01\x12\x16\n" +
	"\x12FLOW_TYPE_RECOVERY\x10\x022\x8d\x03\n" +
	"\vAuthService\x12I\n" +
	"\x0eInitializeFlow\x12\x1a.api.InitializeFlowRequest\x1a\x1b.api.InitializeFlowResponse\x12O\n" +
	"\x10RequestLoginCode\x12\x1c.api.RequestLoginCodeRequest\x1a\x1d.api.RequestLoginCodeResponse\x12=\n" +
	"\n" +
	"SubmitAuth\x12\x16.api.SubmitAuthRequest\x1a\x17.api.SubmitAuthResponse\x121\n" +
	"\x06WhoAmI\x12\x12.api.WhoAmIRequest\x1a\x13.api.WhoAmIResponse\x121\n" +
	"\x06Logout\x12\x12.api.LogoutRequest\x1a\x13.api.LogoutResponse\x12=\n" +
	"\n" +
	"InviteUser\x12\x16.api.InviteUserRequest\x1a\x17.api.InviteUserResponseB\x1eZ\x1cgithub.com/bh90210/super/apib\x06proto3"

var (
	file_api_authservice_proto_rawDescOnce sync.Once
	file_api_authservice_proto_rawDescData []byte
)

func file_api_authservice_proto_rawDescGZIP() []byte {
	file_api_authservice_proto_rawDescOnce.Do(func() {
		file_api_authservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_authservice_proto_rawDesc), len(file_api_authservice_proto_rawDesc)))
	})
	return file_api_authservice_proto_rawDescData
}

var file_api_authservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_authservice_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_authservice_proto_goTypes = []any{
	(FlowType)(0),                    // 0: api.FlowType
	(*InitializeFlowRequest)(nil),    // 1: api.InitializeFlowRequest
	(*InitializeFlowResponse)(nil),   // 2: api.InitializeFlowResponse
	(*RequestLoginCodeRequest)(nil),  // 3: api.RequestLoginCodeRequest
	(*RequestLoginCodeResponse)(nil), // 4: api.RequestLoginCodeResponse
	(*SubmitAuthRequest)(nil),        // 5: api.SubmitAuthRequest
	(*SubmitAuthResponse)(nil),       // 6: api.SubmitAuthResponse
	(*InviteUserRequest)(nil),        // 7: api.InviteUserRequest
	(*InviteUserResponse)(nil),       // 8: api.InviteUserResponse
	(*WhoAmIRequest)(nil),            // 9: api.WhoAmIRequest
	(*WhoAmIResponse)(nil),           // 10: api.WhoAmIResponse
	(*LogoutRequest)(nil),            // 11: api.LogoutRequest
	(*LogoutResponse)(nil),           // 12: api.LogoutResponse
	(*UserIdentity)(nil),             // 13: api.UserIdentity
	nil,                              // 14: api.InviteUserRequest.TraitsEntry
	nil,                              // 15: api.UserIdentity.TraitsEntry
}
var file_api_authservice_proto_depIdxs = []int32{
	0,  // 0: api.InitializeFlowRequest.type:type_name -> api.FlowType
	13, // 1: api.SubmitAuthResponse.identity:type_name -> api.UserIdentity
	14, // 2: api.InviteUserRequest.traits:type_name -> api.InviteUserRequest.TraitsEntry
	13, // 3: api.WhoAmIResponse.identity:type_name -> api.UserIdentity
	15, // 4: api.UserIdentity.traits:type_name -> api.UserIdentity.TraitsEntry
	1,  // 5: api.AuthService.InitializeFlow:input_type -> api.InitializeFlowRequest
	3,  // 6: api.AuthService.RequestLoginCode:input_type -> api.RequestLoginCodeRequest
	5,  // 7: api.AuthService.SubmitAuth:input_type -> api.SubmitAuthRequest
	9,  // 8: api.AuthService.WhoAmI:input_type -> api.WhoAmIRequest
	11, // 9: api.AuthService.Logout:input_type -> api.LogoutRequest
	7,  // 10: api.AuthService.InviteUser:input_type -> api.InviteUserRequest
	2,  // 11: api.AuthService.InitializeFlow:output_type -> api.InitializeFlowResponse
	4,  // 12: api.AuthService.RequestLoginCode:output_type -> api.RequestLoginCodeResponse
	6,  // 13: api.AuthService.SubmitAuth:output_type -> api.SubmitAuthResponse
	10, // 14: api.AuthService.WhoAmI:output_type -> api.WhoAmIResponse
	12, // 15: api.AuthService.Logout:output_type -> api.LogoutResponse
	8,  // 16: api.AuthService.InviteUser:output_type -> api.InviteUserResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_authservice_proto_init() }
func file_api_authservice_proto_init() {
	if File_api_authservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_authservice_proto_rawDesc), len(file_api_authservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_authservice_proto_goTypes,
		DependencyIndexes: file_api_authservice_proto_depIdxs,
		EnumInfos:         file_api_authservice_proto_enumTypes,
		MessageInfos:      file_api_authservice_proto_msgTypes,
	}.Build()
	File_api_authservice_proto = out.File
	file_api_authservice_proto_goTypes = nil
	file_api_authservice_proto_depIdxs = nil
}
