name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'SUPER'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'SUPER'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'SUPER'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: bh90210/wails-build-action@wails-v3
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.24.0'
          wails-version: '2abd05f7834d3d1310a76c6c378842df74fc7f3b'
          sign-sparkle: false
